version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - RUST_LOG=info
      - ETHEREUM_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/demo
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  redis_data:
